### ISSUE TITLE
How do I get the melody data of the dataset？

### ISSUE THREAD

**Issue by li-car-fei** [wazenmai/MIDI-BERT#10]
Hello ! It is a great work!

How do I get the melody data of the dataset ?

**Comment by sophia1488** [comment]
Hi, thank you for your interest!
We use POP909 for melody extraction. For more info, please take a look at [Readme](https://github.com/wazenmai/MIDI-BERT/tree/CP/data_creation).

**Comment by li-car-fei** [comment]
> Hi, thank you for your interest! We use POP909 for melody extraction. For more info, please take a look at [Readme](https://github.com/wazenmai/MIDI-BERT/tree/CP/data_creation).

I found that you didn't use velocity token in pre-training, this doesn't guarantee the integrity of the music, right? 
That means, a song cannot be recovered without the representation of velocity?

**Comment by sophia1488** [comment]
Yes we didn't use velocity token because velocity prediction is one of our downstream tasks.
This work could be extended by incorporating velocity tokens during pre-training, then finetuning the pre-trained model on other downstream tasks.

In order to recover a song for [melody extraction](https://github.com/wazenmai/MIDI-BERT/tree/CP/melody_extraction/midibert), I process a midi to `all events` (with velocity and tempo tokens) and `simplified-CP token` (Bar, Position, Pitch, Duration).
https://github.com/wazenmai/MIDI-BERT/blob/f66da5425c27639bf172ea1ad5229c32dfc21e54/melody_extraction/midibert/midi2CP.py#L34

After inference using `simplified-CP token`, I post-process to get the melody events.
https://github.com/wazenmai/MIDI-BERT/blob/f66da5425c27639bf172ea1ad5229c32dfc21e54/melody_extraction/midibert/extract.py#L108

It's a bit inconvenient, but that's the most intuitive method I can think of under this setting.
Hope it helps.

**Comment by li-car-fei** [comment]
> 

What about downstream tasks at the sentence level? Isn't velocity one of the expressions of the composer and emotion?

[MIDI-BERT/melody_extraction/midibert/midi2CP.py](https://github.com/wazenmai/MIDI-BERT/blob/f66da5425c27639bf172ea1ad5229c32dfc21e54/melody_extraction/midibert/midi2CP.py#L34)
Line 34 in [f66da54](https://github.com/wazenmai/MIDI-BERT/commit/f66da5425c27639bf172ea1ad5229c32dfc21e54)

Is the processing here different from the processing in ‘Compound-Word-Transformer’? In that paper, note information and bar-pos information are distinguished according to a Type-Token.

thanks for your answer

**Comment by sophia1488** [comment]
Hi @li-car-fei, sorry for the delayed reply.
Yes, our CP is different from the original CP.  We only use (Bar, Position, Pitch, Duration), so you'll get a different result if you use their code.
Since our initial goal was to have velocity prediction as one of the downstream tasks and we wanted to use all the data we have for pretraining, adding velocity token sounds like cheating.
But anyway, we plan to release v2 (including velocity and tempo tokens) and re-run all the experiments 🔥 
Please let me know if you have other concerns.

**Comment by li-car-fei** [comment]
> 

Can you provide the code to convert your CP representation back to a midi music file? For example, make velocity the default value.

```python
def write_midi(words, path_outfile, word2event):
    class_keys = word2event.keys()
    midi_obj = miditoolkit.midi.parser.MidiFile()

    bar_cnt = 0

    all_notes = []

    for i in range(len(words)):
        vals = []
        for kidx, key in enumerate(class_keys):
            vals.append(word2event[key][words[i][kidx]])
        # print(vals)

        if vals[0].split(' ')[-1] == 'New':
            bar_cnt += 1
        if (vals[0].split(' ')[-1] == 'New') or (vals[0].split(' ')[-1] == 'Continue'):
            position_ = vals[1].split(' ')[-1]
            if position_ != "<PAD>" and position_ != "<MASK>":
                position = int(position_.split('/')[0]) - 1
            else:
                continue

            duration_ = vals[3].split(' ')[-1]
            if duration_ != "<PAD>" and duration_ != "<MASK>":
                duration = int(duration_) * 60
            else:
                continue
            pitch_ = vals[2].split(' ')[-1]
            if pitch_ != "<PAD>" and pitch_ != "<MASK>":
                pitch = int(pitch_)
            else:
                continue
            st = bar_cnt * BAR_RESOL + position * TICK_RESOL
            et = st + duration
            all_notes.append(miditoolkit.Note(velocity=60, pitch=pitch, start=st, end=et))

    # save midi
    piano_track = Instrument(0, is_drum=False, name='piano')
    piano_track.notes = all_notes
    midi_obj.instruments = [piano_track]
    midi_obj.dump(path_outfile)
```

I tried doing it like above and the music turned out to sound right, but I don't know if it's right.

Thanks for your answers
