### ISSUE TITLE
melody extraction gets empty output

### ISSUE THREAD

**Issue by xuan301** [wazenmai/MIDI-BERT#9]
When I use my own MIDI file, the code runs successfully and there is no error during its running. But the melody it generates is empty, could you tell my how to deal this problem?

[https://drive.google.com/drive/folders/1sQmBtmcKOIFzw-EHFlQ3wgO2oyvRMfeH?usp=sharing](url)
The above is my sample MIDI file, you can try with it.
![image](https://user-images.githubusercontent.com/58766422/194566989-27f4c797-4466-427c-937d-d43850874a92.png)

**Comment by sophia1488** [comment]
Hi, thanks for using our repo!
I'm a bit busy lately.  I'd find some time to look into it within a week and reply, sorry for that :(

**Comment by sophia1488** [comment]
Hi @xuan301, unfortunately, I got the same empty output.
I found that the predictions are mostly accompaniment, and the probabilities for most of that are greater than 90%. At first, I thought all outcomes might be equally likely if the model is uncertain.  Turns out the model is so confident to make a wrong decision by predicting them as accompaniments.
It indicates that the model is not robust enough 😞 

I did a little quick experiment cause I want to know the 2nd most confident prediction, so I manually multiplied the probability score of accompaniment by a small constant.  The result is [here](https://drive.google.com/file/d/1KeFkCUNAk1a6Bz3ferm-b4f_5pN7aUhg/view?usp=sharing).

I understand it's kinda bad to modify the inference matrix.  But now my assumption is that maybe the training dataset (POP909) is too simple for a relatively large model to learn.  
If you have other datasets or methods that may help MidiBERT generalize better, feel free to share.  Thanks!
